/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Login;
import View.Main.Main_Frame;
import com.mysql.cj.protocol.Message;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.*;
/**
 *
 * @author Thinh
 */
public class Login_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Login_Panel
     */
    public Login_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb_Login = new javax.swing.JLabel();
        p_MainLogin = new javax.swing.JPanel();
        lb_UserId = new javax.swing.JLabel();
        lb_Password = new javax.swing.JLabel();
        txt_UserID = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        p_BottomLogin = new javax.swing.JPanel();
        bt_Login = new javax.swing.JButton();
        bt_Register = new javax.swing.JButton();
        bt_Exit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lb_Login.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lb_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Login.setText("Login");
        lb_Login.setToolTipText("");
        add(lb_Login, java.awt.BorderLayout.PAGE_START);

        p_MainLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        p_MainLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p_MainLogin.setLayout(new java.awt.GridBagLayout());

        lb_UserId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_UserId.setLabelFor(txt_UserID);
        lb_UserId.setText("UserID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 10, 8);
        p_MainLogin.add(lb_UserId, gridBagConstraints);

        lb_Password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_Password.setLabelFor(txt_Password);
        lb_Password.setText("Passwrod");
        lb_Password.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 10, 8);
        p_MainLogin.add(lb_Password, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 6);
        p_MainLogin.add(txt_UserID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_MainLogin.add(txt_Password, gridBagConstraints);

        add(p_MainLogin, java.awt.BorderLayout.CENTER);

        bt_Login.setText("Login");
        bt_Login.setActionCommand("");
        bt_Login.setAlignmentY(1.0F);
        bt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LoginActionPerformed(evt);
            }
        });
        p_BottomLogin.add(bt_Login);

        bt_Register.setText("Register");
        bt_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RegisterActionPerformed(evt);
            }
        });
        p_BottomLogin.add(bt_Register);

        bt_Exit.setText("Exit");
        bt_Exit.setActionCommand("");
        bt_Exit.setAlignmentY(1.0F);
        bt_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExitActionPerformed(evt);
            }
        });
        p_BottomLogin.add(bt_Exit);

        add(p_BottomLogin, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LoginActionPerformed
        String userID = txt_UserID.getText();
        String password = txt_Password.getText();       
        User user = User.login(userID, password);     
        if (user != null){
            JOptionPane.showMessageDialog(null, "Login is sucessful.");
        }else{
            JOptionPane.showMessageDialog(null, "UserName or Passwrod is wrong");
            return;
        }
        Login_Frame topFrame = (Login_Frame) SwingUtilities.getWindowAncestor(this);
        View.Main.Home.useid = userID;
        this.setVisible(false);
        topFrame.setVisible(false);
        Main_Frame uf = new Main_Frame();
        uf.setVisible(true);
        topFrame.pack();
    }//GEN-LAST:event_bt_LoginActionPerformed

    private void bt_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_ExitActionPerformed

    private void bt_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RegisterActionPerformed
        // TODO add your handling code here:
        //Main_Frame
        Register newRegister = new Register();
        Login_Frame newFrame = (Login_Frame)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(newRegister);
        newFrame.pack();
    }//GEN-LAST:event_bt_RegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Register;
    private javax.swing.JLabel lb_Login;
    private javax.swing.JLabel lb_Password;
    private javax.swing.JLabel lb_UserId;
    private javax.swing.JPanel p_BottomLogin;
    private javax.swing.JPanel p_MainLogin;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserID;
    // End of variables declaration//GEN-END:variables
}
