/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Login;

import model.UserDB;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;

/**
 *
 * @author Thinh
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    private String EMAIL = "^[A-Za-z0-9+_.-]+@(.+)$";
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Gbt_Status = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_Registy = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb_UserID = new javax.swing.JLabel();
        lb_FullName = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lb_Password = new javax.swing.JLabel();
        lb_Status = new javax.swing.JLabel();
        lb_UserRight = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_UserID = new javax.swing.JTextField();
        txt_FullName = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        rbt_BT = new javax.swing.JRadioButton();
        rbt_LT = new javax.swing.JRadioButton();
        rbt_KT = new javax.swing.JRadioButton();
        rbt_SP = new javax.swing.JRadioButton();
        CB_UserRight = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        bt_Registy.setText("Registy");
        bt_Registy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RegistyActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Registy);

        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Cancel);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lb_UserID.setText("UserID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(lb_UserID, gridBagConstraints);

        lb_FullName.setText("FullName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(lb_FullName, gridBagConstraints);

        lbEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(lbEmail, gridBagConstraints);

        lb_Password.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(lb_Password, gridBagConstraints);

        lb_Status.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(lb_Status, gridBagConstraints);

        lb_UserRight.setText("UserRight");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel2.add(lb_UserRight, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel2.add(txt_Email, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel2.add(txt_UserID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel2.add(txt_FullName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(txt_Password, gridBagConstraints);

        Gbt_Status.add(rbt_BT);
        rbt_BT.setSelected(true);
        rbt_BT.setText("BT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(rbt_BT, gridBagConstraints);

        Gbt_Status.add(rbt_LT);
        rbt_LT.setText("LT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(rbt_LT, gridBagConstraints);

        Gbt_Status.add(rbt_KT);
        rbt_KT.setText("KT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(rbt_KT, gridBagConstraints);

        Gbt_Status.add(rbt_SP);
        rbt_SP.setText("SP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(rbt_SP, gridBagConstraints);

        CB_UserRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(CB_UserRight, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_RegistyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RegistyActionPerformed
        String userid = txt_UserID.getText();
        if (UserDB.getUser(userid) != null){
            JOptionPane.showMessageDialog(null, "UserID is existed.");
            return;
        }
        String fullname = txt_FullName.getText();
        String email = txt_Email.getText();
        String password = txt_Password.getText();
        if (fullname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Full name must not empty");
            return;
        }
        if (!email.matches(EMAIL)){
            JOptionPane.showMessageDialog(null, "Email must is follow form.");
            return;
        }
        if (password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Password must not empty");
            return;
        }
        String status = "";
        if (rbt_BT.isSelected()){
            status = "BT";
        }else if (rbt_KT.isSelected()){
            status = "KT";
        }else if (rbt_LT.isSelected()){
            status = "LT";
        }else if (rbt_SP.isSelected()){
            status = "SP";
        }
        String userright = (String)CB_UserRight.getSelectedItem();
        UserDB.addNewUser(userid, fullname, email, status, status, userright);
        JOptionPane.showMessageDialog(null, "Registy is sucessful.");
        
        Login_Panel login = new Login_Panel();
        Login_Frame newFrame = (Login_Frame)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(login);
        newFrame.pack();
    }//GEN-LAST:event_bt_RegistyActionPerformed

    
    
    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        Login_Panel login = new Login_Panel();
        Login_Frame newFrame = (Login_Frame)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(login);
        newFrame.pack();
    }//GEN-LAST:event_bt_CancelActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_UserRight;
    private javax.swing.ButtonGroup Gbt_Status;
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_Registy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lb_FullName;
    private javax.swing.JLabel lb_Password;
    private javax.swing.JLabel lb_Status;
    private javax.swing.JLabel lb_UserID;
    private javax.swing.JLabel lb_UserRight;
    private javax.swing.JRadioButton rbt_BT;
    private javax.swing.JRadioButton rbt_KT;
    private javax.swing.JRadioButton rbt_LT;
    private javax.swing.JRadioButton rbt_SP;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FullName;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserID;
    // End of variables declaration//GEN-END:variables
}
