/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import model.*;
/**
 *
 * @author Thinh
 */
public class Login_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Login_Panel
     */
    public Login_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Login = new javax.swing.JLabel();
        p_MainLogin = new javax.swing.JPanel();
        lb_Username = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        lb_Password = new javax.swing.JLabel();
        txt_Password = new javax.swing.JTextField();
        p_BottomLogin = new javax.swing.JPanel();
        bt_Login = new javax.swing.JButton();
        bt_Exit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lb_Login.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lb_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Login.setText("Login");
        lb_Login.setToolTipText("");
        add(lb_Login, java.awt.BorderLayout.PAGE_START);

        p_MainLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        p_MainLogin.setLayout(new java.awt.GridLayout(2, 2, 0, 1));

        lb_Username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Username.setText("Username");
        lb_Username.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        p_MainLogin.add(lb_Username);

        txt_Username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_UsernameKeyReleased(evt);
            }
        });
        p_MainLogin.add(txt_Username);

        lb_Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Password.setText("Password");
        lb_Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        p_MainLogin.add(lb_Password);

        txt_Password.setToolTipText("");
        txt_Password.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        p_MainLogin.add(txt_Password);

        add(p_MainLogin, java.awt.BorderLayout.CENTER);

        bt_Login.setText("Login");
        bt_Login.setActionCommand("");
        bt_Login.setAlignmentY(1.0F);
        bt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LoginActionPerformed(evt);
            }
        });
        p_BottomLogin.add(bt_Login);

        bt_Exit.setText("Exit");
        bt_Exit.setActionCommand("");
        bt_Exit.setAlignmentY(1.0F);
        p_BottomLogin.add(bt_Exit);

        add(p_BottomLogin, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsernameKeyReleased
        String username;
        username = txt_Username.getText();
        if ((username.length() != 5) || (username.charAt(0) != 'U')){
           
        }
    }//GEN-LAST:event_txt_UsernameKeyReleased

    private void bt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LoginActionPerformed
        String userName = txt_Username.getText();
        String password = txt_Password.getText();
        
    }//GEN-LAST:event_bt_LoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Login;
    private javax.swing.JLabel lb_Login;
    private javax.swing.JLabel lb_Password;
    private javax.swing.JLabel lb_Username;
    private javax.swing.JPanel p_BottomLogin;
    private javax.swing.JPanel p_MainLogin;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
