/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JComponent;

/**
 *
 * @author Thinh
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPain = new javax.swing.JSplitPane();
        lb_logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        MenuBar_Menu = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Menu_Login = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPain.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IconLogo.jpg"))); // NOI18N
        lb_logo.setText("jLabel1");
        MainPain.setTopComponent(lb_logo);

        jPanel1.setLayout(new java.awt.BorderLayout());
        MainPain.setRightComponent(jPanel1);

        getContentPane().add(MainPain, java.awt.BorderLayout.CENTER);

        jMenu3.setText("File");

        Menu_Login.setText("Login");
        Menu_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_LoginActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Login);

        MenuBar_Menu.add(jMenu3);

        jMenu4.setText("Edit");
        MenuBar_Menu.add(jMenu4);

        setJMenuBar(MenuBar_Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_LoginActionPerformed
        Login_Panel ip = new Login_Panel();
        MainPain.setBottomComponent(ip);
        pack();
    }//GEN-LAST:event_Menu_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane MainPain;
    private javax.swing.JMenuBar MenuBar_Menu;
    private javax.swing.JMenuItem Menu_Login;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_logo;
    // End of variables declaration//GEN-END:variables
}
