/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import chatBox.ChatInterface;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thinh
 */
public class Welcome extends javax.swing.JFrame implements KeyListener{

    String user;
    ChatInterface chat;
    List<String> users = new ArrayList<>();
    /**
     * Creates new form view
     */
    public Welcome(ChatInterface chat){
        initComponents();
        this.chat = chat;
        txt_name.addKeyListener(this);
        setVisible(true);
        setLocationRelativeTo(null);    // to visible the GUI in the middle of the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb_title = new javax.swing.JLabel();
        lb_icon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        bt_name = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 255));
        setPreferredSize(new java.awt.Dimension(300, 200));
        setSize(new java.awt.Dimension(300, 400));

        lb_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_title.setForeground(new java.awt.Color(0, 102, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Welcome to Chatbox");
        getContentPane().add(lb_title, java.awt.BorderLayout.PAGE_START);

        lb_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chatting.png"))); // NOI18N
        getContentPane().add(lb_icon, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lb_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_name.setForeground(new java.awt.Color(51, 102, 255));
        lb_name.setText("Enter name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lb_name, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(txt_name, gridBagConstraints);

        bt_name.setText("Enter");
        bt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(bt_name, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nameActionPerformed
        userLogin();
    }//GEN-LAST:event_bt_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_title;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {  // key event to the text field
            userLogin();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
    
    private void userLogin() {
        user = txt_name.getText();
        try {
            users = chat.getAllUsers();
        } catch (RemoteException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (users.contains(user)) {
            JOptionPane.showMessageDialog(null, "This user is already exists");
            System.exit(0);
        } else {
            try {
                new Chat(chat, user);   // pass the reference "chat" and the logged user's name
            } catch (RemoteException ex) {      // and create new ChatView
                Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
        }
    }
}
