/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.*;
/**
 *
 * @author Thinh
 */
public class P_AddNewStudent extends javax.swing.JPanel {

    /**
     * Creates new form P_AddNewStudent
     */
    public P_AddNewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btG_gender = new javax.swing.ButtonGroup();
        P_Controller = new javax.swing.JPanel();
        Bt_Ok = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();
        P_Contain = new javax.swing.JPanel();
        lb_code1 = new javax.swing.JLabel();
        lb_name1 = new javax.swing.JLabel();
        lb_DateOfBirth1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        CB_Day = new javax.swing.JComboBox<>();
        CB_Month = new javax.swing.JComboBox<>();
        CB_Year = new javax.swing.JComboBox<>();
        RBt_Male = new javax.swing.JRadioButton();
        RBt_Female = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        P_Controller.setLayout(new java.awt.GridBagLayout());

        Bt_Ok.setText("Ok");
        Bt_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_OkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 39, 1, 39);
        P_Controller.add(Bt_Ok, gridBagConstraints);

        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 39, 1, 39);
        P_Controller.add(bt_Cancel, gridBagConstraints);

        add(P_Controller, java.awt.BorderLayout.PAGE_END);

        P_Contain.setLayout(new java.awt.GridBagLayout());

        lb_code1.setText("Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(lb_code1, gridBagConstraints);

        lb_name1.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(lb_name1, gridBagConstraints);

        lb_DateOfBirth1.setText("Date Of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(lb_DateOfBirth1, gridBagConstraints);

        jLabel5.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(txt_code, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(txt_name, gridBagConstraints);

        CB_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(CB_Day, gridBagConstraints);

        CB_Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(CB_Month, gridBagConstraints);

        CB_Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "2000" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(CB_Year, gridBagConstraints);

        btG_gender.add(RBt_Male);
        RBt_Male.setSelected(true);
        RBt_Male.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(RBt_Male, gridBagConstraints);

        btG_gender.add(RBt_Female);
        RBt_Female.setText("Female");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        P_Contain.add(RBt_Female, gridBagConstraints);

        add(P_Contain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        ViewStudent login = new ViewStudent();
        MainFrame newFrame = (MainFrame)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(login);
        newFrame.pack();
    }//GEN-LAST:event_bt_CancelActionPerformed

    private void Bt_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_OkActionPerformed
        String newcode = txt_code.getText();
        if (StudentDB.getStudent(newcode) != null){
            JOptionPane.showMessageDialog(null, "UserID is existed.");
            return;
        }
        String code = txt_code.getText();
        String name = txt_name.getText();
        if (code.isEmpty()){
            JOptionPane.showMessageDialog(null, "Full name must not empty");
            return;
        }
        if (name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Email must is follow form.");
            return;
        }
       
        int gender = 1;
        if (RBt_Male.isSelected()){
            gender = 1;
        }else if (RBt_Female.isSelected()){
            gender = 2;
        }
        
        String date = (String)CB_Day.getSelectedItem();
        String month = (String)CB_Month.getSelectedItem();
        String year = (String)CB_Year.getSelectedItem();
        String dateOfBirth = year + "-" + month + "-" + date; 
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date doB = formatter.parse(dateOfBirth);
            StudentDB.addNewStudent(code, name, doB, gender);
        } catch (ParseException ex) {
            Logger.getLogger(P_AddNewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        JOptionPane.showMessageDialog(null, "Registy is sucessful.");
        
        ViewStudent viewStudent = new ViewStudent();
        MainFrame newFrame = (MainFrame)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(viewStudent);
        newFrame.pack();
    }//GEN-LAST:event_Bt_OkActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Ok;
    private javax.swing.JComboBox<String> CB_Day;
    private javax.swing.JComboBox<String> CB_Month;
    private javax.swing.JComboBox<String> CB_Year;
    private javax.swing.JPanel P_Contain;
    private javax.swing.JPanel P_Controller;
    private javax.swing.JRadioButton RBt_Female;
    private javax.swing.JRadioButton RBt_Male;
    private javax.swing.ButtonGroup btG_gender;
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb_DateOfBirth1;
    private javax.swing.JLabel lb_code1;
    private javax.swing.JLabel lb_name1;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
