/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi;

import View.*;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author Thinh
 */
public class P_ViewStudent extends javax.swing.JPanel {

    DefaultTableModel dtb = new DefaultTableModel();
    
    public P_ViewStudent() throws RemoteException {
        initComponents();
        execute();
    }
    
    private void execute() {
        //setLocationRelativeTo(null);            // to visible the GUI in the middle of the screen
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        refresh();                  // this thread is used to refresh the Manager window by every second 
                    } catch (RemoteException ex) {
                        Logger.getLogger(StudentManagerClient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {                       
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        System.err.println("Error");
                    }
                }
            }
        });
        t1.start();
    }
    
    public void refresh() throws RemoteException {
        StudentManagerImp manager = new StudentManagerImp();
        ArrayList<Student> array = manager.getAllStudent();
        dtb.setRowCount(0);
        dtb = (DefaultTableModel) tb_Student.getModel();
        for (int i = 0; i < array.size(); i++) {
            String gender;
            if (array.get(i).getGender() == 1){
                gender = "Male";
            }else{
                gender = "Female";
            }
            dtb.addRow(new Object[]{
                i , array.get(i).getCode(), array.get(i).getName(),array.get(i).getDateOfBirth(),gender
            });
        }
        tb_Student.setModel(dtb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sp_ViewStudent = new javax.swing.JScrollPane();
        tb_Student = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bt_add = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tb_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Code", "Name", "Date Of Birth", "Gender"
            }
        ));
        Sp_ViewStudent.setViewportView(tb_Student);

        add(Sp_ViewStudent, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        bt_add.setText("Add new Student");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });
        jPanel1.add(bt_add, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        P_AddNewStudent add = new P_AddNewStudent();
        StudentManagerClient newFrame = (StudentManagerClient)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(add);
        newFrame.pack();
    }//GEN-LAST:event_bt_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Sp_ViewStudent;
    private javax.swing.JButton bt_add;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tb_Student;
    // End of variables declaration//GEN-END:variables
}
