/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LogLib;
import model.LogLibDB;
import model.User;
import model.UserDB;

/**
 *
 * @author Thinh
 */
public class BorrowBook extends javax.swing.JPanel {

    DefaultTableModel dtb = new DefaultTableModel();

    /**
     * Creates new form BorrowBook
     */
    public BorrowBook() {
        initComponents();
        ArrayList<LogLib> array = LogLibDB.viewLogByUser(Home.useid);
        dtb = (DefaultTableModel) tb_BorrowBook.getModel();
        for (int i = 0; i < array.size(); i++) {
            if (!array.get(i).isBorrow()) {
                dtb.addRow(new Object[]{
                    array.get(i).getLogID(), array.get(i).getUserID(), array.get(i).getBookID(), array.get(i).getNgayDat()
                });
            }
        }
        tb_BorrowBook.setModel(dtb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lb_BorrowBook = new javax.swing.JLabel();
        P_BorrowBook = new javax.swing.JPanel();
        P_BorrowBookComand = new javax.swing.JPanel();
        bt_BorrowBook = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();
        SP_BorrowBook = new javax.swing.JScrollPane();
        tb_BorrowBook = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lb_BorrowBook.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_BorrowBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_BorrowBook.setText("Borrow Book");
        add(lb_BorrowBook, java.awt.BorderLayout.PAGE_START);

        P_BorrowBook.setLayout(new java.awt.BorderLayout());

        P_BorrowBookComand.setLayout(new java.awt.GridBagLayout());

        bt_BorrowBook.setText("Borrow Book");
        bt_BorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BorrowBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 40, 3, 40);
        P_BorrowBookComand.add(bt_BorrowBook, gridBagConstraints);

        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 40, 3, 40);
        P_BorrowBookComand.add(bt_Cancel, gridBagConstraints);

        P_BorrowBook.add(P_BorrowBookComand, java.awt.BorderLayout.PAGE_START);

        tb_BorrowBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LogID", "UserID", "BookID", "NgayDat"
            }
        ));
        SP_BorrowBook.setViewportView(tb_BorrowBook);

        P_BorrowBook.add(SP_BorrowBook, java.awt.BorderLayout.CENTER);

        add(P_BorrowBook, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        dtb = (DefaultTableModel) tb_BorrowBook.getModel();
        int row = tb_BorrowBook.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please choose log first.");
            return;
        }

        Integer id = (Integer)tb_BorrowBook.getValueAt(row, 0);
        int logid = (Integer) id;
        // remove log when cancel order
        dtb.removeRow(row);
        LogLibDB.deleteLog(logid);
    }//GEN-LAST:event_bt_CancelActionPerformed

    private void bt_BorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BorrowBookActionPerformed
        User user = UserDB.getUser(Home.useid);
        dtb = (DefaultTableModel) tb_BorrowBook.getModel();
        int row = tb_BorrowBook.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please choose log first.");
            return;
        }

        Integer id = (Integer)tb_BorrowBook.getValueAt(row, 0);
        int logid = (Integer) id;
        // update log when borrow book
        user.borrowBook(logid, "U0010");
        dtb.removeRow(row);
    }//GEN-LAST:event_bt_BorrowBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_BorrowBook;
    private javax.swing.JPanel P_BorrowBookComand;
    private javax.swing.JScrollPane SP_BorrowBook;
    private javax.swing.JButton bt_BorrowBook;
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JLabel lb_BorrowBook;
    private javax.swing.JTable tb_BorrowBook;
    // End of variables declaration//GEN-END:variables
}
