/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;


import model.User;
import model.UserDB;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Thinh
 */
public class ChangePassword extends javax.swing.JPanel {

    /**
     * Creates new form P_ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        P_MainChange = new javax.swing.JPanel();
        lb_OldPassword = new javax.swing.JLabel();
        lb_NewPassword = new javax.swing.JLabel();
        lb_Confirm = new javax.swing.JLabel();
        txt_OldPassword = new javax.swing.JPasswordField();
        txt_NewPassWord = new javax.swing.JPasswordField();
        txt_Confirm = new javax.swing.JPasswordField();
        P_Save = new javax.swing.JPanel();
        bt_Save = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change Password");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        P_MainChange.setLayout(new java.awt.GridBagLayout());

        lb_OldPassword.setText("Old Pasword");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        P_MainChange.add(lb_OldPassword, gridBagConstraints);

        lb_NewPassword.setText("New Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        P_MainChange.add(lb_NewPassword, gridBagConstraints);

        lb_Confirm.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        P_MainChange.add(lb_Confirm, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        P_MainChange.add(txt_OldPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        P_MainChange.add(txt_NewPassWord, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        P_MainChange.add(txt_Confirm, gridBagConstraints);

        add(P_MainChange, java.awt.BorderLayout.CENTER);

        P_Save.setLayout(new java.awt.GridBagLayout());

        bt_Save.setText("Save");
        bt_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 37, 2, 37);
        P_Save.add(bt_Save, gridBagConstraints);

        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 37, 2, 37);
        P_Save.add(bt_Cancel, gridBagConstraints);

        add(P_Save, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveActionPerformed
        String oldPassword = txt_OldPassword.getText();
        String newPassword = txt_NewPassWord.getText();
        String confirm  = txt_Confirm.getText();
        if (!confirm.equals(newPassword)){
            JOptionPane.showMessageDialog(null, "Confirm password is wrong.");
            return;
        }
        User updated = UserDB.getUser(Home.useid);
        updated.setPassword(newPassword);
        UserDB.updateUser(updated);
        JOptionPane.showMessageDialog(null, "Change password sucessful.");
    }//GEN-LAST:event_bt_SaveActionPerformed

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        Home home = new Home();
        Main_Frame newFrame = (Main_Frame)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        newFrame.getContentPane().add(home);
        newFrame.pack();
    }//GEN-LAST:event_bt_CancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_MainChange;
    private javax.swing.JPanel P_Save;
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_Confirm;
    private javax.swing.JLabel lb_NewPassword;
    private javax.swing.JLabel lb_OldPassword;
    private javax.swing.JPasswordField txt_Confirm;
    private javax.swing.JPasswordField txt_NewPassWord;
    private javax.swing.JPasswordField txt_OldPassword;
    // End of variables declaration//GEN-END:variables
}
