/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.BookDB;
import model.LogLib;
import model.LogLibDB;

/**
 *
 * @author Thinh
 */
public class History extends javax.swing.JPanel {

    DefaultTableModel dtb = new DefaultTableModel();
    /**
     * Creates new form History
     */
    public History() {
        initComponents();
        ArrayList<LogLib> array = LogLibDB.viewLogByUser(Home.useid);
        dtb = (DefaultTableModel) tb_History.getModel();
        for (int i = 0; i < array.size(); i++) {
            if (array.get(i).isReturn()) {
                dtb.addRow(new Object[]{
                    i, 
                    BookDB.getBook(array.get(i).getBookID()).getTitle(), 
                    array.get(i).getNgayDat(), 
                    array.get(i).getNgayMuon(), 
                    array.get(i).getNgayTra()
                });
            }
        }
        tb_History.setModel(dtb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_History = new javax.swing.JLabel();
        SP_History = new javax.swing.JScrollPane();
        tb_History = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lb_History.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_History.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_History.setText("History");
        add(lb_History, java.awt.BorderLayout.PAGE_START);

        tb_History.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tittle", "Ngày Đặt", "Ngày Mượn", "Ngày Trả"
            }
        ));
        SP_History.setViewportView(tb_History);

        add(SP_History, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SP_History;
    private javax.swing.JLabel lb_History;
    private javax.swing.JTable tb_History;
    // End of variables declaration//GEN-END:variables
}
