/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.BookDB;
import javax.swing.JOptionPane;
import model.User;
import model.UserDB;
/**
 *
 * @author Thinh
 */
public class Home extends javax.swing.JPanel {

    DefaultTableModel dtb = new DefaultTableModel();
    public static String useid = "U0003";

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        ArrayList<Book> array = BookDB.displayAllBooks();
        dtb = (DefaultTableModel) table.getModel();
        for (int i = 0; i < array.size(); i++) {
            dtb.addRow(new Object[]{
                i , array.get(i).getBookID() , array.get(i).getTitle(),array.get(i).getAuthor(),array.get(i).getCategory(),array.get(i).getKeyword()
            });
        }
        table.setModel(dtb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lb_Home = new javax.swing.JLabel();
        P_Comand = new javax.swing.JPanel();
        bt_OderBook = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "BookId", "Tittle", "Author", "Category", "KeyWord"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lb_Home.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Home.setText("Home");
        jPanel2.add(lb_Home, java.awt.BorderLayout.CENTER);

        bt_OderBook.setText("Order Book");
        bt_OderBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OderBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_ComandLayout = new javax.swing.GroupLayout(P_Comand);
        P_Comand.setLayout(P_ComandLayout);
        P_ComandLayout.setHorizontalGroup(
            P_ComandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_ComandLayout.createSequentialGroup()
                .addGap(0, 305, Short.MAX_VALUE)
                .addComponent(bt_OderBook, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        P_ComandLayout.setVerticalGroup(
            P_ComandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_OderBook, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.add(P_Comand, java.awt.BorderLayout.PAGE_END);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_OderBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OderBookActionPerformed
        int row = table.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please choose book first.");
            return;
        }

        String bookid = (String)table.getValueAt(row, 1);
        System.out.println(bookid);
        UserDB.getUser(useid).orderBook(bookid);
        JOptionPane.showMessageDialog(null, "Order Book sucessful.");
    }//GEN-LAST:event_bt_OderBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_Comand;
    private javax.swing.JButton bt_OderBook;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Home;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
