/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import View.Login.Login_Frame;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Thinh
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
        //setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        Home home = new Home();
        this.getContentPane().add(home);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Pain = new javax.swing.JPanel();
        MenuBar_Main = new javax.swing.JMenuBar();
        Menu_Menu = new javax.swing.JMenu();
        MI_Home = new javax.swing.JMenuItem();
        MI_SearchBooks = new javax.swing.JMenuItem();
        MI_BorrowBook = new javax.swing.JMenuItem();
        MI_ReturnBook = new javax.swing.JMenuItem();
        MI_View = new javax.swing.JMenuItem();
        Menu_User = new javax.swing.JMenu();
        MI_ChangeInformation = new javax.swing.JMenuItem();
        MI_ChangePassword = new javax.swing.JMenuItem();
        MI_Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_Pain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Main_Pain, java.awt.BorderLayout.CENTER);

        MenuBar_Main.setBackground(new java.awt.Color(51, 153, 255));
        MenuBar_Main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Menu_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Main/icons8-menu-24.png"))); // NOI18N
        Menu_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_MenuActionPerformed(evt);
            }
        });

        MI_Home.setText("Home");
        MI_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_HomeActionPerformed(evt);
            }
        });
        Menu_Menu.add(MI_Home);

        MI_SearchBooks.setText("Search Books");
        MI_SearchBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_SearchBooksActionPerformed(evt);
            }
        });
        Menu_Menu.add(MI_SearchBooks);

        MI_BorrowBook.setText("Borrow Book");
        MI_BorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_BorrowBookActionPerformed(evt);
            }
        });
        Menu_Menu.add(MI_BorrowBook);

        MI_ReturnBook.setText("Return Book");
        MI_ReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ReturnBookActionPerformed(evt);
            }
        });
        Menu_Menu.add(MI_ReturnBook);

        MI_View.setText("View History");
        MI_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ViewActionPerformed(evt);
            }
        });
        Menu_Menu.add(MI_View);

        MenuBar_Main.add(Menu_Menu);

        Menu_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Main/icons8-automatic-32.png"))); // NOI18N

        MI_ChangeInformation.setText("Change information");
        MI_ChangeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ChangeInformationActionPerformed(evt);
            }
        });
        Menu_User.add(MI_ChangeInformation);

        MI_ChangePassword.setText("Change Password");
        MI_ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_ChangePasswordActionPerformed(evt);
            }
        });
        Menu_User.add(MI_ChangePassword);

        MI_Logout.setText("Logout");
        MI_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_LogoutActionPerformed(evt);
            }
        });
        Menu_User.add(MI_Logout);

        MenuBar_Main.add(Box.createHorizontalGlue());

        MenuBar_Main.add(Menu_User);

        setJMenuBar(MenuBar_Main);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MI_ChangeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ChangeInformationActionPerformed
        UpdateUser change = new UpdateUser();
        //this.getContentPane().setVisible(false);
        this.getContentPane().removeAll();
        this.getContentPane().add(change);
        this.pack();
    }//GEN-LAST:event_MI_ChangeInformationActionPerformed

    private void MI_ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ChangePasswordActionPerformed
        ChangePassword changePassword = new ChangePassword();
        this.getContentPane().removeAll();
        this.getContentPane().add(changePassword);
        this.pack();
    }//GEN-LAST:event_MI_ChangePasswordActionPerformed

    private void MI_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_LogoutActionPerformed
        this.setVisible(false);
        Login_Frame uf = new Login_Frame();
        uf.setVisible(true);
    }//GEN-LAST:event_MI_LogoutActionPerformed

    private void Menu_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_MenuActionPerformed
        
    }//GEN-LAST:event_Menu_MenuActionPerformed

    private void MI_SearchBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_SearchBooksActionPerformed
        SearchingBook search = new SearchingBook();
        this.getContentPane().removeAll();
        this.getContentPane().add(search);
        this.pack();
    }//GEN-LAST:event_MI_SearchBooksActionPerformed

    private void MI_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_HomeActionPerformed
        Home home = new Home();
        this.getContentPane().removeAll();
        this.getContentPane().add(home);
        this.pack();
    }//GEN-LAST:event_MI_HomeActionPerformed

    private void MI_BorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_BorrowBookActionPerformed
        BorrowBook borrow = new BorrowBook();
        this.getContentPane().removeAll();
        this.getContentPane().add(borrow);
        this.pack();
    }//GEN-LAST:event_MI_BorrowBookActionPerformed

    private void MI_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ViewActionPerformed
        History history = new History();
        this.getContentPane().removeAll();
        this.getContentPane().add(history);
        this.pack();
    }//GEN-LAST:event_MI_ViewActionPerformed

    private void MI_ReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_ReturnBookActionPerformed
        ReturnBook returnbook = new ReturnBook();
        this.getContentPane().removeAll();
        this.getContentPane().add(returnbook);
        this.pack();
    }//GEN-LAST:event_MI_ReturnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_BorrowBook;
    private javax.swing.JMenuItem MI_ChangeInformation;
    private javax.swing.JMenuItem MI_ChangePassword;
    private javax.swing.JMenuItem MI_Home;
    private javax.swing.JMenuItem MI_Logout;
    private javax.swing.JMenuItem MI_ReturnBook;
    private javax.swing.JMenuItem MI_SearchBooks;
    private javax.swing.JMenuItem MI_View;
    private javax.swing.JPanel Main_Pain;
    private javax.swing.JMenuBar MenuBar_Main;
    private javax.swing.JMenu Menu_Menu;
    private javax.swing.JMenu Menu_User;
    // End of variables declaration//GEN-END:variables
}
