/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BookDB;
import model.LogLib;
import model.LogLibDB;
import model.User;
import model.UserDB;

/**
 *
 * @author Thinh
 */
public class ReturnBook extends javax.swing.JPanel {

    DefaultTableModel dtb = new DefaultTableModel();
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
        ArrayList<LogLib> array = LogLibDB.viewLogByUser(Home.useid);
        System.out.println(array.get(0).getNgayMuon());
        dtb = (DefaultTableModel) tb_ReturnBook.getModel();
        for (int i = 0; i < array.size(); i++) {
            if (!array.get(i).isReturn()) {
                dtb.addRow(new Object[]{
                    array.get(i).getLogID(), 
                    BookDB.getBook(array.get(i).getBookID()).getTitle(), 
                    array.get(i).getNgayMuon(), 
                    array.get(i).getNgayPTra()
                });
            }
        }
        tb_ReturnBook.setModel(dtb);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ReturnBook = new javax.swing.JLabel();
        P_ReturnBook = new javax.swing.JPanel();
        P_BorrowBookComand = new javax.swing.JPanel();
        bt_ReturnBook = new javax.swing.JButton();
        SP_ReturnBook = new javax.swing.JScrollPane();
        tb_ReturnBook = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lb_ReturnBook.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_ReturnBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ReturnBook.setText("Return Book");
        add(lb_ReturnBook, java.awt.BorderLayout.PAGE_START);

        P_ReturnBook.setLayout(new java.awt.BorderLayout());

        bt_ReturnBook.setText("Return book");
        bt_ReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ReturnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_BorrowBookComandLayout = new javax.swing.GroupLayout(P_BorrowBookComand);
        P_BorrowBookComand.setLayout(P_BorrowBookComandLayout);
        P_BorrowBookComandLayout.setHorizontalGroup(
            P_BorrowBookComandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_BorrowBookComandLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(bt_ReturnBook)
                .addContainerGap())
        );
        P_BorrowBookComandLayout.setVerticalGroup(
            P_BorrowBookComandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_BorrowBookComandLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(bt_ReturnBook))
        );

        P_ReturnBook.add(P_BorrowBookComand, java.awt.BorderLayout.PAGE_START);

        tb_ReturnBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LogID", "Tittle", "NgayMuon", "NgayPtra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SP_ReturnBook.setViewportView(tb_ReturnBook);

        P_ReturnBook.add(SP_ReturnBook, java.awt.BorderLayout.CENTER);

        add(P_ReturnBook, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ReturnBookActionPerformed
        User user = UserDB.getUser(Home.useid);
        dtb = (DefaultTableModel) tb_ReturnBook.getModel();
        int row = tb_ReturnBook.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(null, "Please choose log first.");
            return;
        }

        Integer id = (Integer)tb_ReturnBook.getValueAt(row, 0);
        int logid = (Integer) id;
        // remove log when cancel order
        dtb.removeRow(row);
        user.returnBook(logid);
        JOptionPane.showMessageDialog(null, "Return book successful.");
    }//GEN-LAST:event_bt_ReturnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_BorrowBookComand;
    private javax.swing.JPanel P_ReturnBook;
    private javax.swing.JScrollPane SP_ReturnBook;
    private javax.swing.JButton bt_ReturnBook;
    private javax.swing.JLabel lb_ReturnBook;
    private javax.swing.JTable tb_ReturnBook;
    // End of variables declaration//GEN-END:variables
}
