/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.User;
import model.UserDB;

/**
 *
 * @author Thinh
 */
public class UpdateUser extends javax.swing.JPanel {

    private String EMAIL = "^[A-Za-z0-9+_.-]+@(.+)$";
    /**
     * Creates new form UpdateUser
     */
    public UpdateUser() {
        initComponents(); 
        getOldUser();
    }
    
    private void getOldUser(){
        User olduser = UserDB.getUser(Home.useid);
        txt_FullName.setText(olduser.getFullName());
        txt_Email.setText(olduser.getEmail());
        String status = olduser.getStatus();
        if (status.equalsIgnoreCase("BT")){
            rbt_BT.setSelected(true);
        }else if (status.equalsIgnoreCase("LT")){
            rbt_LT.setSelected(true);
        }else if (status.equalsIgnoreCase("SP")){
            rbt_SP.setSelected(true);
        }else if (status.equalsIgnoreCase("KT")){
            rbt_KT.setSelected(true);
        }   
        CB_UserRight.getModel().setSelectedItem(olduser.getUserRight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gbt_Status = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_FullName = new javax.swing.JLabel();
        lb_Email = new javax.swing.JLabel();
        lb_Status = new javax.swing.JLabel();
        lb_UserRight = new javax.swing.JLabel();
        txt_FullName = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        CB_UserRight = new javax.swing.JComboBox<>();
        rbt_BT = new javax.swing.JRadioButton();
        rbt_LT = new javax.swing.JRadioButton();
        rbt_KT = new javax.swing.JRadioButton();
        rbt_SP = new javax.swing.JRadioButton();
        P_Save = new javax.swing.JPanel();
        bt_Save = new javax.swing.JButton();
        bt_Reset = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Change Information");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lb_FullName.setText("FullName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 2, 10);
        jPanel1.add(lb_FullName, gridBagConstraints);

        lb_Email.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 2, 10);
        jPanel1.add(lb_Email, gridBagConstraints);

        lb_Status.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 2, 10);
        jPanel1.add(lb_Status, gridBagConstraints);

        lb_UserRight.setText("UserRight");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 2, 10);
        jPanel1.add(lb_UserRight, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 2, 10);
        jPanel1.add(txt_FullName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 2, 10);
        jPanel1.add(txt_Email, gridBagConstraints);

        CB_UserRight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 10);
        jPanel1.add(CB_UserRight, gridBagConstraints);

        gbt_Status.add(rbt_BT);
        rbt_BT.setText("BT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 7, 4, 7);
        jPanel1.add(rbt_BT, gridBagConstraints);

        gbt_Status.add(rbt_LT);
        rbt_LT.setText("LT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(rbt_LT, gridBagConstraints);

        gbt_Status.add(rbt_KT);
        rbt_KT.setText("KT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 9, 4, 9);
        jPanel1.add(rbt_KT, gridBagConstraints);

        gbt_Status.add(rbt_SP);
        rbt_SP.setText("SP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 9, 4, 9);
        jPanel1.add(rbt_SP, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        P_Save.setLayout(new java.awt.GridBagLayout());

        bt_Save.setText("Save");
        bt_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 5);
        P_Save.add(bt_Save, gridBagConstraints);

        bt_Reset.setText("Reset");
        bt_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 5);
        P_Save.add(bt_Reset, gridBagConstraints);

        add(P_Save, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveActionPerformed
        User updated = UserDB.getUser(Home.useid);
        String fullname = txt_FullName.getText();
        String email =  txt_Email.getText();
        if (fullname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Full name must not empty.");
            return;
        }
        if (!email.matches(EMAIL)){
            JOptionPane.showMessageDialog(null, "Please enter email follow form [a-z]%@[a-z]%.[a-z]%");
            return;
        }
        updated.setEmail(email);
        updated.setFullName(fullname);
        
        String status = "";
        if (rbt_BT.isSelected()){
            status = "BT";
        }else if (rbt_KT.isSelected()){
            status = "KT";
        }else if (rbt_LT.isSelected()){
            status = "LT";
        }else if (rbt_SP.isSelected()){
            status = "SP";
        }
        updated.setStatus(status);
        String userright = (String)CB_UserRight.getSelectedItem();
        updated.setUserRight(Integer.parseInt(userright.trim()));
        UserDB.updateUser(updated);
        JOptionPane.showMessageDialog(null, "Update sucessful.");
    }//GEN-LAST:event_bt_SaveActionPerformed

    private void bt_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ResetActionPerformed
        getOldUser();
    }//GEN-LAST:event_bt_ResetActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_UserRight;
    private javax.swing.JPanel P_Save;
    private javax.swing.JButton bt_Reset;
    private javax.swing.JButton bt_Save;
    private javax.swing.ButtonGroup gbt_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_FullName;
    private javax.swing.JLabel lb_Status;
    private javax.swing.JLabel lb_UserRight;
    private javax.swing.JRadioButton rbt_BT;
    private javax.swing.JRadioButton rbt_KT;
    private javax.swing.JRadioButton rbt_LT;
    private javax.swing.JRadioButton rbt_SP;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FullName;
    // End of variables declaration//GEN-END:variables
}
